<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.jd4yBTl' shared service.

return $this->privates['.service_locator.jd4yBTl'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('entityManager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}, 'keyword' => function (): \App\Entity\Keyword {
    return ($this->privates['.errored..service_locator.jd4yBTl.App\Entity\Keyword'] ?? $this->load('getKeywordService.php'));
}));
