<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.5aix426' shared service.

return $this->privates['.service_locator.5aix426'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('carRepository' => function (): \App\Repository\CarRepository {
    return ($this->privates['App\Repository\CarRepository'] ?? $this->load('getCarRepositoryService.php'));
}));
