<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.SAgtiTs' shared service.

return $this->privates['.service_locator.SAgtiTs'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('handler' => function (): \App\Services\ImageHandler {
    return ($this->privates['App\Services\ImageHandler'] ?? $this->privates['App\Services\ImageHandler'] = new \App\Services\ImageHandler($this->targetDirs[3]));
}, 'manager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}));
