<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..9V3Qw.' shared service.

return $this->privates['.service_locator..9V3Qw.'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('entityManager' => function () {
    return ($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php'));
}, 'user' => function (): \App\Entity\User {
    return ($this->privates['.errored..service_locator..9V3Qw..App\Entity\User'] ?? $this->load('getUserService.php'));
}, 'userRepository' => function (): \App\Repository\UserRepository {
    return ($this->privates['App\Repository\UserRepository'] ?? $this->load('getUserRepositoryService.php'));
}));
