<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.aw5t5sp' shared service.

return $this->privates['.service_locator.aw5t5sp'] = new \Symfony\Component\DependencyInjection\ServiceLocator(array('car' => function (): \App\Entity\Car {
    return ($this->privates['.errored..service_locator.aw5t5sp.App\Entity\Car'] ?? $this->load('getCar2Service.php'));
}));
