<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\AdminController::admin' => function () {
    return ($this->privates['.service_locator.pDN53fn'] ?? $this->load('get_ServiceLocator_PDN53fnService.php'));
}, 'App\\Controller\\AdminController::deleteUser' => function () {
    return ($this->privates['.service_locator..9V3Qw.'] ?? $this->load('get_ServiceLocator__9V3Qw_Service.php'));
}, 'App\\Controller\\IndexController::add' => function () {
    return ($this->privates['.service_locator.SAgtiTs'] ?? $this->load('get_ServiceLocator_SAgtiTsService.php'));
}, 'App\\Controller\\IndexController::delete' => function () {
    return ($this->privates['.service_locator.HXu8sPO'] ?? $this->load('get_ServiceLocator_HXu8sPOService.php'));
}, 'App\\Controller\\IndexController::deleteKeyword' => function () {
    return ($this->privates['.service_locator.jd4yBTl'] ?? $this->load('get_ServiceLocator_Jd4yBTlService.php'));
}, 'App\\Controller\\IndexController::edit' => function () {
    return ($this->privates['.service_locator.HXu8sPO'] ?? $this->load('get_ServiceLocator_HXu8sPOService.php'));
}, 'App\\Controller\\IndexController::index' => function () {
    return ($this->privates['.service_locator.5aix426'] ?? $this->load('get_ServiceLocator_5aix426Service.php'));
}, 'App\\Controller\\IndexController::show' => function () {
    return ($this->privates['.service_locator.aw5t5sp'] ?? $this->load('get_ServiceLocator_Aw5t5spService.php'));
}, 'App\\Controller\\SearchController::searchCar' => function () {
    return ($this->privates['.service_locator.5aix426'] ?? $this->load('get_ServiceLocator_5aix426Service.php'));
}, 'App\\Controller\\SecurityController::login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\SecurityController::registration' => function () {
    return ($this->privates['.service_locator.evt2lKM'] ?? $this->load('get_ServiceLocator_Evt2lKMService.php'));
}, 'App\\Controller\\SecurityController::validateToken' => function () {
    return ($this->privates['.service_locator.OnuXj9Z'] ?? $this->load('get_ServiceLocator_OnuXj9ZService.php'));
}, 'App\\Controller\\AdminController:admin' => function () {
    return ($this->privates['.service_locator.pDN53fn'] ?? $this->load('get_ServiceLocator_PDN53fnService.php'));
}, 'App\\Controller\\AdminController:deleteUser' => function () {
    return ($this->privates['.service_locator..9V3Qw.'] ?? $this->load('get_ServiceLocator__9V3Qw_Service.php'));
}, 'App\\Controller\\IndexController:add' => function () {
    return ($this->privates['.service_locator.SAgtiTs'] ?? $this->load('get_ServiceLocator_SAgtiTsService.php'));
}, 'App\\Controller\\IndexController:delete' => function () {
    return ($this->privates['.service_locator.HXu8sPO'] ?? $this->load('get_ServiceLocator_HXu8sPOService.php'));
}, 'App\\Controller\\IndexController:deleteKeyword' => function () {
    return ($this->privates['.service_locator.jd4yBTl'] ?? $this->load('get_ServiceLocator_Jd4yBTlService.php'));
}, 'App\\Controller\\IndexController:edit' => function () {
    return ($this->privates['.service_locator.HXu8sPO'] ?? $this->load('get_ServiceLocator_HXu8sPOService.php'));
}, 'App\\Controller\\IndexController:index' => function () {
    return ($this->privates['.service_locator.5aix426'] ?? $this->load('get_ServiceLocator_5aix426Service.php'));
}, 'App\\Controller\\IndexController:show' => function () {
    return ($this->privates['.service_locator.aw5t5sp'] ?? $this->load('get_ServiceLocator_Aw5t5spService.php'));
}, 'App\\Controller\\SearchController:searchCar' => function () {
    return ($this->privates['.service_locator.5aix426'] ?? $this->load('get_ServiceLocator_5aix426Service.php'));
}, 'App\\Controller\\SecurityController:login' => function () {
    return ($this->privates['.service_locator.ypl2DZZ'] ?? $this->load('get_ServiceLocator_Ypl2DZZService.php'));
}, 'App\\Controller\\SecurityController:registration' => function () {
    return ($this->privates['.service_locator.evt2lKM'] ?? $this->load('get_ServiceLocator_Evt2lKMService.php'));
}, 'App\\Controller\\SecurityController:validateToken' => function () {
    return ($this->privates['.service_locator.OnuXj9Z'] ?? $this->load('get_ServiceLocator_OnuXj9ZService.php'));
}))), ($this->privates['debug.stopwatch'] ?? $this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true)));
