<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fidry_alice_data_fixtures.persistence.persister.doctrine' shared service.

include_once $this->targetDirs[3].'\\vendor\\theofidry\\alice-data-fixtures\\src\\Persistence\\PersisterInterface.php';
include_once $this->targetDirs[3].'\\vendor\\nelmio\\alice\\src\\IsAServiceTrait.php';
include_once $this->targetDirs[3].'\\vendor\\theofidry\\alice-data-fixtures\\src\\Bridge\\Doctrine\\Persister\\ObjectManagerPersister.php';

return $this->services['fidry_alice_data_fixtures.persistence.persister.doctrine'] = new \Fidry\AliceDataFixtures\Bridge\Doctrine\Persister\ObjectManagerPersister(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
