<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fidry_alice_data_fixtures.persistence.purger_factory.doctrine' shared service.

include_once $this->targetDirs[3].'\\vendor\\theofidry\\alice-data-fixtures\\src\\Persistence\\PurgerInterface.php';
include_once $this->targetDirs[3].'\\vendor\\theofidry\\alice-data-fixtures\\src\\Persistence\\PurgerFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\nelmio\\alice\\src\\IsAServiceTrait.php';
include_once $this->targetDirs[3].'\\vendor\\theofidry\\alice-data-fixtures\\src\\Bridge\\Doctrine\\Purger\\Purger.php';

return $this->services['fidry_alice_data_fixtures.persistence.purger_factory.doctrine'] = new \Fidry\AliceDataFixtures\Bridge\Doctrine\Purger\Purger(($this->services['doctrine.orm.default_entity_manager'] ?? $this->load('getDoctrine_Orm_DefaultEntityManagerService.php')));
