<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'Faker\Generator' shared service.

include_once $this->targetDirs[3].'\\vendor\\fzaninotto\\faker\\src\\Faker\\Factory.php';
include_once $this->targetDirs[3].'\\vendor\\fzaninotto\\faker\\src\\Faker\\Provider\\Base.php';
include_once $this->targetDirs[3].'\\src\\Faker\\CarProvider.php';
include_once $this->targetDirs[3].'\\src\\Faker\\UserProvider.php';
include_once $this->targetDirs[3].'\\vendor\\nelmio\\alice\\src\\Faker\\Provider\\AliceProvider.php';

$this->services['Faker\Generator'] = $instance = \Faker\Factory::create('en_US');

$instance->seed(1);
$instance->addProvider(new \App\Faker\CarProvider($instance));
$instance->addProvider(new \App\Faker\UserProvider($instance, ($this->services['security.password_encoder'] ?? $this->load('getSecurity_PasswordEncoderService.php'))));
$instance->addProvider(new \Nelmio\Alice\Faker\Provider\AliceProvider());

return $instance;
