<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hautelook_alice.resolver.bundle' shared service.

include_once $this->targetDirs[3].'\\vendor\\hautelook\\alice-bundle\\src\\BundleResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\nelmio\\alice\\src\\IsAServiceTrait.php';
include_once $this->targetDirs[3].'\\vendor\\hautelook\\alice-bundle\\src\\Resolver\\Bundle\\NoBundleResolver.php';
include_once $this->targetDirs[3].'\\vendor\\hautelook\\alice-bundle\\src\\Resolver\\Bundle\\SimpleBundleResolver.php';

return $this->services['hautelook_alice.resolver.bundle'] = new \Hautelook\AliceBundle\Resolver\Bundle\NoBundleResolver(new \Hautelook\AliceBundle\Resolver\Bundle\SimpleBundleResolver(($this->services['kernel'] ?? $this->get('kernel', 1))));
