<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hautelook_alice.locator' shared service.

include_once $this->targetDirs[3].'\\vendor\\hautelook\\alice-bundle\\src\\FixtureLocatorInterface.php';
include_once $this->targetDirs[3].'\\vendor\\nelmio\\alice\\src\\IsAServiceTrait.php';
include_once $this->targetDirs[3].'\\vendor\\hautelook\\alice-bundle\\src\\Locator\\EnvironmentlessFilesLocator.php';
include_once $this->targetDirs[3].'\\vendor\\hautelook\\alice-bundle\\src\\Locator\\EnvDirectoryLocator.php';

return $this->services['hautelook_alice.locator'] = new \Hautelook\AliceBundle\Locator\EnvironmentlessFilesLocator(new \Hautelook\AliceBundle\Locator\EnvDirectoryLocator('fixtures', $this->getParameter('hautelook_alice.root_dirs')));
