<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Services\ImageHandler' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Services\\ImageHandler.php';

return $this->privates['App\Services\ImageHandler'] = new \App\Services\ImageHandler($this->targetDirs[3]);
