<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'nelmio_alice.files_loader' shared service.

include_once $this->targetDirs[3].'\\vendor\\nelmio\\alice\\src\\FilesLoaderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\nelmio\\alice\\src\\IsAServiceTrait.php';
include_once $this->targetDirs[3].'\\vendor\\nelmio\\alice\\src\\Loader\\SimpleFilesLoader.php';

$a = ($this->services['nelmio_alice.data_loader'] ?? $this->load('getNelmioAlice_DataLoaderService.php'));

if (isset($this->services['nelmio_alice.files_loader'])) {
    return $this->services['nelmio_alice.files_loader'];
}

return $this->services['nelmio_alice.files_loader'] = new \Nelmio\Alice\Loader\SimpleFilesLoader(($this->privates['nelmio_alice.file_parser.runtime_cache'] ?? $this->load('getNelmioAlice_FileParser_RuntimeCacheService.php')), $a);
