<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.OnuXj9Z.App\Entity\Token' shared service.

throw new RuntimeException('Cannot autowire service ".service_locator.OnuXj9Z": it references class "App\\Entity\\Token" but no such service exists.');
