<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCRtCsiN\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCRtCsiN/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerCRtCsiN.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerCRtCsiN\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerCRtCsiN\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'CRtCsiN',
    'container.build_id' => 'df532d8a',
    'container.build_time' => 1581935066,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerCRtCsiN');
